// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return web; // Use web config for Windows testing
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKQ6zsTYAYtQnZ8L1dQOpBGTjrODK0y4A',
    appId: '1:34302340063:web:699dcc4772c6240c86726a',
    messagingSenderId: '34302340063',
    projectId: 'adgen-pharmacy',
    storageBucket: 'adgen-pharmacy.firebasestorage.app',
    authDomain: 'adgen-pharmacy.firebaseapp.com',
    measurementId: 'G-L4KSBPM7FG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbMHv-27jU31ygN1wNDibn4a5hA16H7wo',
    appId: '1:34302340063:android:a21dfb198477ca2386726a',
    messagingSenderId: '34302340063',
    projectId: 'adgen-pharmacy',
    storageBucket: 'adgen-pharmacy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKQ6zsTYAYtQnZ8L1dQOpBGTjrODK0y4A',
    appId: '1:34302340063:ios:699dcc4772c6240c86726a',
    messagingSenderId: '34302340063',
    projectId: 'adgen-pharmacy',
    storageBucket: 'adgen-pharmacy.firebasestorage.app',
    iosBundleId: 'com.adgen.pharmacyErp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKQ6zsTYAYtQnZ8L1dQOpBGTjrODK0y4A',
    appId: '1:34302340063:ios:699dcc4772c6240c86726a',
    messagingSenderId: '34302340063',
    projectId: 'adgen-pharmacy',
    storageBucket: 'adgen-pharmacy.firebasestorage.app',
    iosBundleId: 'com.adgen.pharmacyErp',
  );
}
