import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import '../../core/theme/app_colors.dart';
import '../../core/theme/app_typography.dart';
import '../../core/theme/app_spacing.dart';
import '../../core/providers/auth_provider.dart';
import '../../core/providers/sale_return_provider.dart';
import '../../core/providers/inventory_provider.dart';
import '../../core/utils/formatters.dart';
import '../../shared/models/sales_bill_model.dart';
import '../../shared/models/return_model.dart';
import '../../shared/widgets/app_card.dart';

class SaleReturnScreen extends ConsumerStatefulWidget {
  final SalesBillModel originalBill;

  const SaleReturnScreen({super.key, required this.originalBill});

  @override
  ConsumerState<SaleReturnScreen> createState() => _SaleReturnScreenState();
}

class _SaleReturnScreenState extends ConsumerState<SaleReturnScreen> {
  // Map: productId+batch → controller for return qty
  final Map<String, TextEditingController> _qtyControllers = {};
  // Which items are checked for return
  final Map<String, bool> _selected = {};

  SaleReturnReason _reason = SaleReturnReason.wrongMedicine;
  String _refundMethod = 'cash';
  final _notesCtrl = TextEditingController();
  final _reasonNotesCtrl = TextEditingController();
  bool _saving = false;

  SalesBillModel get bill => widget.originalBill;

  @override
  void initState() {
    super.initState();
    for (final item in bill.items) {
      final key = _itemKey(item);
      _qtyControllers[key] = TextEditingController(
          text: item.quantity.toStringAsFixed(0));
      _selected[key] = false;
    }
  }

  @override
  void dispose() {
    for (final c in _qtyControllers.values) c.dispose();
    _notesCtrl.dispose();
    _reasonNotesCtrl.dispose();
    super.dispose();
  }

  String _itemKey(SalesItem item) => '${item.productId}_${item.batchNumber}';

  double _returnQtyFor(SalesItem item) {
    final key = _itemKey(item);
    if (_selected[key] != true) return 0;
    final v = double.tryParse(_qtyControllers[key]?.text ?? '0') ?? 0;
    return v.clamp(0, item.quantity);
  }

  double get _totalRefund {
    double total = 0;
    for (final item in bill.items) {
      final qty = _returnQtyFor(item);
      if (qty <= 0) continue;
      final gross = item.rate * qty;
      final discount = gross * item.discountPercent / 100;
      total += gross - discount;
    }
    return total;
  }

  double get _totalGstReversed {
    double total = 0;
    for (final item in bill.items) {
      final qty = _returnQtyFor(item);
      if (qty <= 0) continue;
      final gross = item.rate * qty;
      final discount = gross * item.discountPercent / 100;
      final amount = gross - discount;
      total += amount - (amount / (1 + item.gstPercent / 100));
    }
    return total;
  }

  int get _selectedCount =>
      _selected.values.where((v) => v).length;

  Future<void> _save() async {
    if (_selectedCount == 0) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('Select at least one item to return'),
        backgroundColor: AppColors.error,
      ));
      return;
    }
    if (_totalRefund <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
        content: Text('Return quantity must be greater than zero'),
        backgroundColor: AppColors.error,
      ));
      return;
    }

    setState(() => _saving = true);

    final user = ref.read(authNotifierProvider).value;
    final inventory = ref.read(inventoryProvider).valueOrNull ?? [];
    final inventoryMap = {for (final inv in inventory) inv.productId: inv};

    // Build return items
    final returnItems = <SaleReturnItem>[];
    for (final item in bill.items) {
      final qty = _returnQtyFor(item);
      if (qty <= 0) continue;
      // Find purchase rate from inventory batch
      final invItem = inventoryMap[item.productId];
      final batch = invItem?.batches
          .where((b) => b.batchNumber == item.batchNumber)
          .firstOrNull;
      returnItems.add(SaleReturnItem(
        productId: item.productId,
        productName: item.productName,
        batchNumber: item.batchNumber,
        expiryDate: item.expiryDate,
        mrp: item.mrp,
        rate: item.rate,
        purchaseRate: batch?.purchaseRate ?? 0,
        gstPercent: item.gstPercent,
        returnQty: qty,
        packQty: qty / item.packSize,
        packSize: item.packSize,
        discountPercent: item.discountPercent,
        division: item.division,
      ));
    }

    final returnModel = SaleReturnModel(
      creditNoteNumber: '', // generated by provider
      originalBillId: bill.id!,
      originalInvoiceNumber: bill.invoiceNumber,
      customerId: bill.customerId ?? bill.customerName,
      customerName: bill.customerName,
      customerPhone: bill.customerPhone,
      returnDate: DateTime.now(),
      createdAt: DateTime.now(),
      createdByUid: user?.uid ?? '',
      createdByName: user?.name ?? '',
      items: returnItems,
      totalRefundAmount: _totalRefund,
      totalGstReversed: _totalGstReversed,
      reason: _reason,
      reasonNotes: _reasonNotesCtrl.text.trim().isNotEmpty
          ? _reasonNotesCtrl.text.trim()
          : null,
      refundMethod: _refundMethod,
      notes: _notesCtrl.text.trim().isNotEmpty ? _notesCtrl.text.trim() : null,
    );

    final error = await ref
        .read(saleReturnNotifierProvider.notifier)
        .createSaleReturn(returnModel);

    setState(() => _saving = false);

    if (!mounted) return;
    if (error != null) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text('Error: $error'),
        backgroundColor: AppColors.error,
      ));
    } else {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(
        content: Text(
            'Credit note created. Refund: ${AppFormatters.formatCurrency(_totalRefund)}'),
        backgroundColor: AppColors.success,
      ));
      context.pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.surface,
        elevation: 0,
        title: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Sale Return', style: AppTypography.h3),
            Text('Against ${bill.invoiceNumber}',
                style: AppTypography.caption),
          ],
        ),
        actions: [
          if (_saving)
            const Padding(
              padding: EdgeInsets.all(16),
              child: SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(strokeWidth: 2),
              ),
            )
          else
            TextButton.icon(
              onPressed: _save,
              icon: const Icon(Icons.check_rounded),
              label: const Text('Create Return'),
              style: TextButton.styleFrom(
                foregroundColor: AppColors.primary,
                textStyle: const TextStyle(fontWeight: FontWeight.w700),
              ),
            ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(AppSpacing.lg),
        children: [
          // ── Original Bill Info ──────────────────────────────────────────
          AppCard(
            padding: const EdgeInsets.all(AppSpacing.md),
            child: Row(children: [
              const Icon(Icons.receipt_long_rounded,
                  color: AppColors.primary, size: 20),
              const SizedBox(width: AppSpacing.sm),
              Expanded(
                child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Original Invoice: ${bill.invoiceNumber}',
                          style: AppTypography.labelLarge),
                      Text(
                        '${bill.customerName} • ${DateFormat('dd MMM yyyy').format(bill.saleDate)} • ${AppFormatters.formatCurrency(bill.grandTotal)}',
                        style: AppTypography.caption,
                      ),
                    ]),
              ),
            ]),
          ),

          const SizedBox(height: AppSpacing.lg),
          Text('Select Items to Return', style: AppTypography.h3),
          const SizedBox(height: AppSpacing.sm),
          Text(
            'Enter the quantity being returned. Max is what was originally sold.',
            style: AppTypography.bodySmall,
          ),
          const SizedBox(height: AppSpacing.md),

          // ── Item List ──────────────────────────────────────────────────
          ...bill.items.map((item) {
            final key = _itemKey(item);
            final isSelected = _selected[key] ?? false;
            return _ReturnItemRow(
              item: item,
              isSelected: isSelected,
              controller: _qtyControllers[key]!,
              onToggle: (v) => setState(() => _selected[key] = v),
              onQtyChanged: () => setState(() {}),
            );
          }),

          const SizedBox(height: AppSpacing.xl),
          const Divider(),
          const SizedBox(height: AppSpacing.md),

          // ── Return Reason ──────────────────────────────────────────────
          Text('Return Reason *', style: AppTypography.labelLarge),
          const SizedBox(height: AppSpacing.sm),
          DropdownButtonFormField<SaleReturnReason>(
            value: _reason,
            decoration: const InputDecoration(
              border: OutlineInputBorder(),
              contentPadding:
                  EdgeInsets.symmetric(horizontal: 12, vertical: 10),
            ),
            items: SaleReturnReason.values
                .map((r) => DropdownMenuItem(
                      value: r,
                      child: Text(r.displayName,
                          style: AppTypography.body),
                    ))
                .toList(),
            onChanged: (v) => setState(() => _reason = v!),
          ),
          const SizedBox(height: AppSpacing.md),
          if (_reason == SaleReturnReason.other) ...[
            TextField(
              controller: _reasonNotesCtrl,
              decoration: const InputDecoration(
                labelText: 'Specify reason',
                border: OutlineInputBorder(),
              ),
            ),
            const SizedBox(height: AppSpacing.md),
          ],

          // ── Refund Method ──────────────────────────────────────────────
          Text('Refund Method *', style: AppTypography.labelLarge),
          const SizedBox(height: AppSpacing.sm),
          SegmentedButton<String>(
            segments: const [
              ButtonSegment(value: 'cash', label: Text('Cash'), icon: Icon(Icons.money_rounded, size: 16)),
              ButtonSegment(value: 'upi', label: Text('UPI'), icon: Icon(Icons.phone_android_rounded, size: 16)),
              ButtonSegment(value: 'credit_note', label: Text('Credit Note'), icon: Icon(Icons.note_alt_rounded, size: 16)),
            ],
            selected: {_refundMethod},
            onSelectionChanged: (s) => setState(() => _refundMethod = s.first),
            style: SegmentedButton.styleFrom(
              selectedBackgroundColor: AppColors.primaryContainer,
              selectedForegroundColor: AppColors.primary,
            ),
          ),

          const SizedBox(height: AppSpacing.md),

          // ── Notes ──────────────────────────────────────────────────────
          TextField(
            controller: _notesCtrl,
            decoration: const InputDecoration(
              labelText: 'Additional notes (optional)',
              border: OutlineInputBorder(),
            ),
            maxLines: 2,
          ),

          const SizedBox(height: AppSpacing.xxl),

          // ── Return Summary ─────────────────────────────────────────────
          AppCard(
            child: Column(children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Items Selected', style: AppTypography.body),
                  Text('$_selectedCount items',
                      style: AppTypography.labelLarge),
                ],
              ),
              const SizedBox(height: AppSpacing.sm),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('GST Reversed', style: AppTypography.body),
                  Text(
                    AppFormatters.formatCurrency(_totalGstReversed),
                    style: AppTypography.numeric
                        .copyWith(color: AppColors.warning),
                  ),
                ],
              ),
              const Divider(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Text('Total Refund Amount', style: AppTypography.h3),
                  Text(
                    AppFormatters.formatCurrency(_totalRefund),
                    style: AppTypography.numericLarge
                        .copyWith(color: AppColors.success),
                  ),
                ],
              ),
            ]),
          ),
          const SizedBox(height: 40),
        ],
      ),
    );
  }
}

// ─── Return Item Row ──────────────────────────────────────────────────────────
class _ReturnItemRow extends StatelessWidget {
  final SalesItem item;
  final bool isSelected;
  final TextEditingController controller;
  final ValueChanged<bool> onToggle;
  final VoidCallback onQtyChanged;

  const _ReturnItemRow({
    required this.item,
    required this.isSelected,
    required this.controller,
    required this.onToggle,
    required this.onQtyChanged,
  });

  @override
  Widget build(BuildContext context) {
    return AppCard(
      padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.md, vertical: AppSpacing.sm),
      child: Row(children: [
        Checkbox(
          value: isSelected,
          onChanged: (v) => onToggle(v ?? false),
          activeColor: AppColors.primary,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(4)),
        ),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(item.productName,
                  style: AppTypography.labelLarge,
                  overflow: TextOverflow.ellipsis),
              Text(
                'Batch: ${item.batchNumber} | Qty sold: ${item.quantity.toStringAsFixed(0)} | Rate: ${AppFormatters.formatCurrency(item.rate)}',
                style: AppTypography.caption,
              ),
            ],
          ),
        ),
        if (isSelected)
          SizedBox(
            width: 80,
            child: TextFormField(
              controller: controller,
              keyboardType: TextInputType.number,
              textAlign: TextAlign.center,
              style: AppTypography.numeric,
              inputFormatters: [FilteringTextInputFormatter.digitsOnly],
              decoration: InputDecoration(
                isDense: true,
                contentPadding:
                    const EdgeInsets.symmetric(horizontal: 8, vertical: 8),
                border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8)),
                hintText: 'Qty',
                hintStyle: AppTypography.caption,
              ),
              onChanged: (_) => onQtyChanged(),
            ),
          ),
        if (!isSelected)
          Text(
            AppFormatters.formatCurrency(item.lineTotal),
            style: AppTypography.numeric
                .copyWith(color: AppColors.textSecondary),
          ),
      ]),
    );
  }
}
